version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - goimports
    # - gofmt
    - gofumpt

linters:
  enable:
    - errcheck
    - ineffassign
    - staticcheck
    - govet
    # - revive
    - gocritic
    - misspell
    - unconvert
    - unused
    - gosec
    - gocyclo
    - funlen
  exclusions:
    generated: strict
    paths: 
      - internal/ui/.*
    rules:
      - path: _test.go
        linters:
          - gosec
          - errcheck
          - gocyclo
          - funlen

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
    gocyclo:
      min-complexity: 25
    funlen:
      lines: 100
      statements: 50
