services:
  db:
    image: postgis/postgis
    restart: always
    # ports:
    #   - 5432:5432
    env_file: ".env"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms
    ports:
      - "8080:8080"
    env_file: ".env"
