version: "3"

vars:
  TAILWIND_CMD:
    sh: "node_modules/.bin/tailwindcss"

  install-tools:
    desc: Install required Go tools (sqlc, templ, goose) and Node modules
    cmds:
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - npm install tailwindcss

  generate:
    desc: Generate sqlc and templ code
    cmds:
      - sqlc generate
      - templ generate

  setup:
    desc: Install tools, generate code
    cmds:
      - task: install-tools
      - task: generate

  dev:
    desc: Start development server with hot reload
    cmds:
      - task --parallel tailwind templ

  run:
    desc: Start development server with hot reload
    cmds:
      - docker compose down
      - docker compose up --build -d
