version: "3"

vars:
  TAILWIND_CMD:
    sh: "node_modules/.bin/tailwindcss"

tasks:
  install-tools:
    desc: Install required Go tools (sqlc, templ, goose) and Node modules
    cmds:
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install github.com/pressly/goose/v3/cmd/goose@latest
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - npm install tailwindcss

  generate:
    desc: Generate sqlc, templ and protobuf code
    cmds:
      - task: sqlc:generate
      - templ generate
      - task: generate-proto

  generate-proto:
    desc: Generate protobuf
    cmds: 
      - protoc --proto_path=/usr/local/include/:. --proto_path=proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/tms.proto

  setup:
    desc: Install tools, generate code
    cmds:
      - task: install-tools
      - task: generate

  dev:
    desc: Start development server with hot reload
    cmds:
      - task --parallel tailwind templ

  run:
    desc: Start development server with hot reload
    cmds:
      - docker compose down
      - docker compose up --build -d

  fmt:
    desc: Format code files
    cmds:
      - templ fmt internal/ui/*
      - golangci-lint fmt ./...
  
  check:
    desc: run linters and checkers
    cmds:
      - task: sqlc:check
      - go vet ./...
      - golangci-lint run ./...

  sqlc:check:
    dir: internal/db
    desc: check sqlc files
    cmds:
      - sqlc compile ./...
      - sqlc vet ./...

  sqlc:generate:
    dir: internal/db
    desc: generate sqlc files
    cmds:
      - task: sqlc:check
      - sqlc generate